# Generated by Django 5.1.5 on 2025-01-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctor-img/', verbose_name='Добавить фото')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_birth', models.DateField(verbose_name='Дата рождение')),
                ('tags', models.CharField(choices=[('Директор', 'Директор'), ('Администратор', 'Администратор'), ('Стоматолог', 'Стоматолог'), ('Рентгенолог', 'Рентгенолог'), ('Педиатр', 'Педиатр'), ('Хирург', 'Хирург'), ('Пациент', 'Пациент')], max_length=100, verbose_name='Теги')),
                ('gender', models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=50, verbose_name='Пол')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон номер')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон номер')),
                ('director', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.director', verbose_name='Директор')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Телефон номер')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('date_appointment', models.DateField(verbose_name='Дата записи')),
                ('gender', models.CharField(choices=[('Женский', 'Женский'), ('Мужской', 'Мужской')], max_length=50, verbose_name='Пол')),
                ('date_birth', models.DateField(verbose_name='Дата рождение')),
                ('complaints', models.TextField(verbose_name='Жалобы')),
                ('time', models.CharField(choices=[('08:00-09:00', '08:00-09:00'), ('09:00-10:00', '09:00-10:00'), ('10:00-11:00', '10:00-11:00'), ('11:00-12:00', '11:00-12:00'), ('12:00-13:00', '12:00-13:00'), ('13:00-14:00', '13:00-14:00'), ('14:00-15:00', '14:00-15:00'), ('15:00-16:00', '15:00-16:00'), ('16:00-17:00', '16:00-17:00'), ('17:00-18:00', '17:00-18:00')], max_length=100, verbose_name='Время')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='admin_panel.doctor', verbose_name='Запись к врачу')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service-img/', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услгу')),
                ('price', models.CharField(max_length=30, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_panel.category', verbose_name='Категория')),
            ],
        ),
    ]
